name: pr1_news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.4.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
